const state={transactions:[],summary:{},goals:[],budgets:[]};
const inr=new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',minimumFractionDigits:0,maximumFractionDigits:2});
const $=s=>document.querySelector(s); const money=n=>inr.format(Number(n)||0); const month=new Date().toISOString().slice(0,7);
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2300)}
async function api(path,options){try{const response=await fetch(path,options);if(!response.ok)throw Error('Request failed');return response.status===204?null:response.json()}catch(error){toast('Could not connect to FLUX');throw error}}
function renderSummary(){const s=state.summary;$('#balance').textContent=money(s.balance);$('#income').textContent=money(s.income);$('#expense').textContent=money(s.expense);$('#entries').textContent=s.entries||0;$('#month-label').textContent=new Date().toLocaleDateString('en-IN',{month:'long',year:'numeric'});const cats=Object.entries(s.categories||{});$('#chart').innerHTML=cats.length?cats.map(([name,value])=>`<div class="bar-group" title="${name}: ${money(value)}"><div class="bar expense" style="height:${Math.max(4,Math.min(100,value/Math.max(s.expense,1)*100))}%"></div></div>`).join(''):'<p class="eyebrow">No expense data yet. Add your first entry.</p>'}
function transactionMarkup(item){const debit=item.amount<0;return `<article class="transaction"><div class="transaction-info"><strong>${escapeHtml(item.merchant)}</strong><small>${item.date} · ${escapeHtml(item.category||'Unclassified')}</small></div><span class="amount ${debit?'debit':'credit'}">${debit?'−':''}${money(Math.abs(item.amount))}</span></article>`}
function renderTransactions(){const list=state.transactions;$('#transaction-list').innerHTML=list.length?list.map(transactionMarkup).join(''):'<p class="eyebrow">No transactions yet.</p>';const pending=list.filter(x=>!x.classified);$('#pending-count').textContent=pending.length?`${pending.length} waiting`:'';$('#pending').innerHTML=pending.slice(0,3).map(item=>`<div class="pending-card"><strong>${money(Math.abs(item.amount))}</strong><p>${escapeHtml(item.merchant)}</p><div>${['Food','Groceries','Transport','Shopping','Bills','Other'].map(c=>`<button class="chip" data-classify="${item.id}" data-category="${c}">${c}</button>`).join('')}</div></div>`).join('')||'<p class="eyebrow">You are caught up.</p>'}
function renderGoals(){const list=state.goals;$('#goal-list').innerHTML=list.map(goal=>`<div class="goal"><div class="goal-head"><strong>${goal.emoji} ${escapeHtml(goal.name)}</strong><span>${money(goal.saved)} / ${money(goal.target)}</span></div><div class="progress"><i style="width:${Math.min(100,goal.saved/goal.target*100)}%"></i></div></div>`).join('')||'<p class="eyebrow">Create a goal to give your savings a direction.</p>'}
function renderBudgets(){$('#budget-list').innerHTML=state.budgets.map(b=>{const spent=state.summary.categories?.[b.category]||0;return `<div class="budget"><div class="budget-head"><strong>${b.category}</strong><span>${money(spent)} / ${money(b.monthly_limit)}</span></div><div class="progress"><i style="width:${Math.min(100,spent/b.monthly_limit*100)}"></i></div></div>`}).join('')||'<p class="eyebrow">Budgets appear here when configured through the API.</p>'}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
async function refresh(){[state.transactions,state.summary,state.goals,state.budgets]=await Promise.all([api(`/api/transactions?month=${month}`),api(`/api/summary?month=${month}`),api('/api/goals'),api('/api/budgets')]);renderSummary();renderTransactions();renderGoals();renderBudgets()}
function switchTab(tab){document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('hidden',p.id!==tab));document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab))}
document.addEventListener('click',async event=>{const tab=event.target.dataset.tab;if(tab)switchTab(tab);if(event.target.dataset.classify){await api('/api/classify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:event.target.dataset.classify,category:event.target.dataset.category})});toast('Saved as '+event.target.dataset.category);refresh()}});
$('#theme').onclick=()=>{const next=document.documentElement.dataset.theme==='light'?'dark':'light';document.documentElement.dataset.theme=next;localStorage.theme=next};
$('#entry-form').onsubmit=async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.target));data.amount=Number(data.amount);await api('/api/transactions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});event.target.reset();toast('Entry saved');switchTab('overview');refresh()};
$('#goal-form').onsubmit=async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.target));data.target=Number(data.target);await api('/api/goals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});event.target.reset();toast('Goal created');switchTab('goals');refresh()};
$('#search').oninput=async event=>{state.transactions=await api(`/api/transactions?month=${month}&q=${encodeURIComponent(event.target.value)}`);renderTransactions()};
document.documentElement.dataset.theme=localStorage.theme|| (matchMedia('(prefers-color-scheme:light)').matches?'light':'dark');$('#today').textContent=new Date().toLocaleDateString('en-IN',{day:'2-digit',month:'short'});refresh();
